---
inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-rubycw
  - rubocop-thread_safety
  - rubocop-md
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 4.0
  DefaultFormatter: fuubar
  NewCops: enable
  SuggestExtensions: false
  CacheRootDirectory: 'tmp/'
  MaxFilesInCache: 65536
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Include:
    - '**/*.rb'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.md'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - 'Capfile'
  Exclude:
    - 'db/schema.rb'
    - 'db/cache_schema.rb'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'sbin/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

# Department-wide disables for high-level control
Metrics:
  Enabled: false

Layout:
  Enabled: true

# Customizations and specific overrides
Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/Debugger:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Rubycw/Rubycw:
  Exclude:
    - '**/*.md'

Naming/FileName:
  Exclude:
    - '**/CHANGELOG.md'
    - '**/README.md'
    - '**/*.md'
    - 'node_modules/**/*'

RSpec:
  Enabled: true

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10 # Allow more flexibility in complex integration specs

Rails:
  Enabled: true

Rails/Output:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/DangerousColumnNames:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/BlockDelimiters:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/Semicolon:
  Enabled: false
