---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rubycw
  - rubocop-thread_safety

AllCops:
  CacheRootDirectory: 'tmp/'
  DefaultFormatter: fuubar
  DisabledByDefault: false
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  MaxFilesInCache: 65536
  NewCops: enable
  TargetRubyVersion: 3.2
  UseCache: true
  Include:
    - 'Capfile'
    - 'Gemfile'
    - 'config.ru'
    - 'config/**/*.rb'
  Exclude:
    - '**/.DS_Store'
    - 'bin/**/*'
    - 'sbin/**/*'
    - '_backup/**/*'

# Layout/LineLength: {Enabled: false}
Lint/EmptyBlock: {Enabled: false}
Lint/SuppressedException: {Enabled: false}
Metrics/BlockLength: {Enabled: false}
Naming/InclusiveLanguage: {Enabled: false}
Style/BlockDelimiters: {Enabled: false}
Style/Documentation: {Enabled: false}
Style/FrozenStringLiteralComment: {Enabled: true, SafeAutoCorrect: true}
Style/MultilineBlockChain: {Enabled: false}
Style/RescueModifier: {Enabled: false}
Style/RescueStandardError: {Enabled: false}
