---
inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rubycw
  - rubocop-thread_safety
  - rubocop-md
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-minitest

AllCops:
  CacheRootDirectory: 'tmp/'
  DefaultFormatter: fuubar
  DisabledByDefault: false
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  MaxFilesInCache: 65536
  NewCops: enable
  TargetRubyVersion: 4.0
  UseCache: true
  Include:
    - '**/*.md'
    - 'Capfile'
    - 'Gemfile'
    - 'config.ru'
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'blorgh/**/*.rb'
  Exclude:
    - 'db/schema.rb'
    - 'db/cache_schema.rb'
    - '**/.DS_Store'
    - 'bin/**/*'
    - 'sbin/**/*'

Layout/EmptyLineAfterGuardClause: {Enabled: false}
Layout/EmptyLines: {Enabled: false}
Layout/LineLength: {Enabled: false}
Lint/Debugger: {Enabled: false}
Lint/EmptyBlock: {Enabled: false}
Lint/EmptyClass: {Enabled: false}
Lint/SuppressedException: {Enabled: false}
Metrics/AbcSize: {Enabled: false}
Metrics/BlockLength: {Enabled: false}
Metrics/CyclomaticComplexity: {Enabled: false}
Metrics/MethodLength: {Enabled: false}
Metrics/ModuleLength: {Enabled: false}
Metrics/PerceivedComplexity: {Enabled: false}
Naming/InclusiveLanguage: {Enabled: false}
RSpec/ContextWording: {Enabled: false}
RSpec/EmptyExampleGroup: {Enabled: false}
RSpec/ExampleLength: {Enabled: false}
RSpec/SpecFilePathFormat: {Enabled: false}
RSpec/SpecFilePathSuffix: {Enabled: false}
RSpec/MultipleDescribes: {Enabled: false}
RSpec/MultipleExpectations: {Enabled: false}
RSpec/NoExpectationExample: {Enabled: false}
RSpec/RepeatedExampleGroupBody: {Enabled: false}
Rails/BulkChangeTable: {Enabled: false}
Rails/CreateTableWithTimestamps: {Enabled: false}
Rails/I18nLocaleTexts: {Enabled: false}
Rails/ReversibleMigration: {Enabled: false}
Style/AccessorGrouping: {Enabled: false}
Style/BlockDelimiters: {Enabled: false}
Style/Documentation: {Enabled: false}
Style/FrozenStringLiteralComment: {Enabled: true, SafeAutoCorrect: true}
Style/MultilineBlockChain: {Enabled: false}
Style/RescueModifier: {Enabled: false}
Style/RescueStandardError: {Enabled: false}
Style/Semicolon: {Enabled: false}
Rails/Output: {Enabled: false}

Rubycw/Rubycw:
  Exclude:
    - '**/*.md'

Naming/FileName:
  Exclude:
    - '**/CHANGELOG.md'
    - '**/README.md'
    - 'blorgh/Gemfile'

ThreadSafety/DirChdir:
  Exclude:
    - 'blorgh/test/dummy/bin/setup'

Rails/DangerousColumnNames:
  Enabled: false # Many legacy migrations use :id explicitly for external IDs

Style/OneClassPerFile:
  Exclude:
    - 'config/application.rb'
