# frozen_string_literal: true

module Searches
  TERMS = [
    'a11y',
    'agile',
    'airbrake',
    'ansible',
    'apache',
    'api',
    'aws',
    'backbone.js',
    'bash',
    'bootstrap',
    'capistrano',
    'ccnet',
    'centos',
    'chargify',
    'circle ci',
    'clojure',
    'codesmith api',
    'coffeescript',
    'couchdb',
    'css',
    'cucumber',
    'devops',
    'digitalocean',
    'docker',
    'ec2',
    'elasticsearch',
    'ember.js',
    'emberjs',
    'eruby',
    'etl',
    'facebook graph api',
    'graph api',
    'fail2ban',
    'git',
    'github api',
    'github',
    'gitlab',
    'go',
    'golang',
    'google analytics',
    'hadoop',
    'heroku',
    'html',
    'html5',
    'http',
    'hubot',
    'instagram api',
    'java',
    'javascript',
    'jira',
    'jquery',
    'jruby',
    'json api',
    'json',
    'jsonapi',
    'jwt',
    'kafka',
    'kubernetes',
    'linux',
    'lisp',
    'lodash',
    'logentries',
    'markdown',
    'memcached',
    'middleware',
    'mongodb',
    'mongrel',
    'monit',
    'mssql',
    'mysql',
    'new relic',
    'nginx',
    'node.js',
    'nodejs',
    'openstack',
    'passenger',
    'php',
    'phpunit',
    'postgres',
    'postgresql',
    'prolog',
    'puma',
    'puppet',
    'python',
    'qunit',
    'rails',
    'raphael.js',
    'rds',
    'react',
    'redis',
    'redux',
    'resque',
    'rest',
    'riak',
    'rollbar',
    'rspec',
    'ruby on rails',
    'ruby',
    'rust',
    's3',
    'sass',
    'scala',
    'scrum',
    'semaphore ci',
    'sendgrid api',
    'shell',
    'sidekiq',
    'soap',
    'sql',
    'stripe',
    'subversion',
    'sumo logic',
    't-sql',
    'thin',
    'transact-sql',
    'trello',
    'twitter api',
    'typescript',
    'ubuntu',
    'uml',
    'underscore.js',
    'unicorn',
    'vagrant',
    'vertica',
    'vim',
    'viml',
    'vmware',
    'web api',
    'xhtml',
    'xml',
    'yaml',
    'z shell',
    'zsh'
  ].uniq.shuffle.freeze

  SEARCHES = {
    'hackernews' => [],
    'indeed' => [],
    'monster' => TERMS.shuffle.freeze,
    'nexxt' => [],
    'remoteok' => [],
    'remotepython' => [],
    'stackoverflow' => TERMS.shuffle.freeze,
    'weworkremotely' => []
  }.freeze

  module_function

  def searches
    SEARCHES.each_pair.each_with_object([]) do |(k, v), o|
      o << [k, 'programming']
      v.each { |term| o << [k, term] }
    end.shuffle.freeze
  end
end
