#!/bin/bash
cd "$(dirname "$0")/.."
echo "--- Starting Remotive Job Fetch ---"
docker-compose exec -T web bin/rails runner - <<'EOF'
  Remotive::Fetcher.new.call
  JobBoards::Syncer.new.call
EOF
echo "--- Done ---"
