#!/usr/bin/env sh
cd "$(dirname "$0")/.." || exit
echo "--- Starting Remotive Job Fetch ---"
docker-compose exec -T web bin/rails runner - <<'EOF'
  Remotive::Fetcher.new.call
  JobBoards::Syncer.new.call
EOF
echo "--- Done ---"
