#!/bin/bash
cd "$(dirname "$0")/.."
echo "--- Starting WWR Job Fetch ---"
docker-compose exec -T web bin/rails runner - <<'EOF'
  Wwr::Fetcher.new.call
  JobBoards::Syncer.new.call
EOF
echo "--- Done ---"
