---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 16
  username: wwworkremote

development:
  <<: *default
  database: wwworkremote_development

test:
  <<: *default
  database: wwworkremote_test

production:
  <<: *default
  database: wwworkremote_production
