---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: outlier_jobs_development
  # url: <%= ENV.fetch('OUTLIER_JOBS_DATABASE_URL', 'postgres://outlier_jobs:window.snow@malina103/outlier_jobs_production') %>

test:
  <<: *default
  database: outlier_jobs_test

production:
  <<: *default
  url: <%= ENV.fetch('OUTLIER_JOBS_DATABASE_URL', 'postgres://outlier_jobs:window.snow@malina103/outlier_jobs_production') %>
