---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  # database: wwwork_remote_development
  url: <%= ENV.fetch('WWWORK_REMOTE_DATABASE_URL', 'postgres://wwwork_remote:window.snow@malina108/wwwork_remote_production') %>

test:
  <<: *default
  database: wwwork_remote_test

production:
  <<: *default
  url: <%= ENV.fetch('WWWORK_REMOTE_DATABASE_URL', 'postgres://wwwork_remote:window.snow@malina108/wwwork_remote_production') %>
