default: &default
  adapter: postgresql
  encoding: unicode
  reconnect: true
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>

development:
  primary:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres:password@localhost:5432/wwworkremote_development" } %>

test:
  <<: *default
  database: wwworkremote_test

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://deploy@localhost/wwworkremote_production" } %>
