---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  # database: wwworkremote_development
  url: <%= ENV.fetch('WWWORKREMOTE_DATABASE_URL', 'postgres://wwworkremote:window.snow@malina108/wwworkremote_production') %>

test:
  <<: *default
  database: wwworkremote_test

production:
  <<: *default
  url: <%= ENV.fetch('WWWORKREMOTE_DATABASE_URL', 'postgres://wwworkremote:window.snow@malina108/wwworkremote_production') %>
