---
common: &default_settings
  license_key: 86b73816aaec65d6f5fa01bc9583051dda514535
  app_name: WwworkRemote::Core
  distributed_tracing:
    enabled: true
  log_level: info

development:
  <<: *default_settings
  app_name: WwworkRemote::Core (Development)

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
