default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  scheduler:
    polling_interval: 5
  workers:
    - queues: "heavy"
      threads: 1
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    - queues: "light"
      threads: 2
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    - queues: "default"
      threads: 2
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    - queues: "broadcasts"
      threads: 1
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    - queues: ["low", "solid_queue_recurring"]
      threads: 1
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 1

development:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 1 # How often to check for concurrency availability
  scheduler:
    polling_interval: 5
  workers:
    - queues: "heavy"
      threads: 2
      polling_interval: 0.1
    - queues: "light"
      threads: 5
      polling_interval: 0.1
    - queues: "default"
      threads: 3
      polling_interval: 0.1
    - queues: "broadcasts"
      threads: 2
      polling_interval: 0.1
    - queues: ["low", "solid_queue_recurring"]
      threads: 1
      polling_interval: 1
  # Concurrency controls to prevent LLM starvation
  # limit: total number of concurrent jobs for this group across all workers
  concurrency_limits:
    heavyweight: 2
    mediumweight: 5
    lightweight: 20

test:
  <<: *default

production:
  <<: *default
