# .rails_best_practices.yml
# See: https://github.com/flyerhzm/rails_best_practices

# Ignore generated/third-party files
ignore_files:
  - 'db/schema.rb'
  - 'Gemfile.lock'
  - 'blorgh/**/*'
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'spec/**/*'

# Specific rules
AddIndexChecker: { }
AlwaysAddDbIndexChecker: { }
CheckSaveReturnValueChecker: { }
CheckReturnValueUsedChecker: { }
ComplexEmailAddressChecker: { }
DryBundlerChecker: { }
HashSyntaxChecker: { }
IsolateSeedDataChecker: { }
KeepFindersOnTheirOwnModelChecker: { }
LawOfDemeterChecker: { enabled: false }
LongLineCheck: { max_line_length: 160 }
MoveCodeIntoControllerChecker: { }
MoveCodeIntoHelperChecker: { array_count: 3 }
MoveCodeIntoModelChecker: { use_count: 5 }
MoveModelLogicIntoModelChecker: { enabled: false }
NeedlessDeepNestingChecker: { nested_count: 2 }
NotRespecTokenizeChecker: { }
NotUseDefaultRouteChecker: { }
NotUseTimeAgoInWordsChecker: { enabled: false }
OveruseRouteCustomizationsChecker: { customize_count: 3 }
ProtectMassAssignmentChecker: { }
RemoveEmptyHelpersChecker: { }
RemoveTabChecker: { }
RemoveTrailingWhitespaceChecker: { }
RemoveUnusedMethodsInControllersChecker: { except_methods: [] }
RemoveUnusedMethodsInHelpersChecker: { except_methods: [] }
RemoveUnusedMethodsInModelsChecker: { except_methods: [] }
ReplaceComplexCreationWithFactoryMethodChecker: { attribute_count: 5 }
ReplaceInstanceVariableWithLocalVariableChecker: { }
RestrictAutoGeneratedRoutesChecker: { }
SimplifyRenderInControllersChecker: { }
SimplifyRenderInViewsChecker: { }
UseBeforeFilterChecker: { customize_count: 3 }
UseModelAssociationChecker: { }
UseMultipartAlternativeAsContentTypeOfEmailChecker: { }
UseParenthesesInMethodDefChecker: { }
UseQueryAttributeChecker: { }
UseSayWithTimeInMigrationsChecker: { }
UseScopeChecker: { }
UseTurboLinksChecker: { }
