# frozen_string_literal: true

TASKS = %w[
  ./exe/hackernews
  ./exe/indeed
  ./exe/monster\ "a11y"
  ./exe/monster\ "agile"
  ./exe/monster\ "airbrake"
  ./exe/monster\ "ansible"
  ./exe/monster\ "apache"
  ./exe/monster\ "api"
  ./exe/monster\ "aws"
  ./exe/monster\ "backbone.js"
  ./exe/monster\ "bash"
  ./exe/monster\ "bootstrap"
  ./exe/monster\ "capistrano"
  ./exe/monster\ "ccnet"
  ./exe/monster\ "centos"
  ./exe/monster\ "chargify"
  ./exe/monster\ "circle\ ci"
  ./exe/monster\ "clojure"
  ./exe/monster\ "codesmith\ api"
  ./exe/monster\ "coffeescript"
  ./exe/monster\ "couchdb"
  ./exe/monster\ "css"
  ./exe/monster\ "cucumber"
  ./exe/monster\ "devops"
  ./exe/monster\ "digitalocean"
  ./exe/monster\ "docker"
  ./exe/monster\ "ec2"
  ./exe/monster\ "elasticsearch"
  ./exe/monster\ "ember.js"
  ./exe/monster\ "emberjs"
  ./exe/monster\ "eruby"
  ./exe/monster\ "etl"
  ./exe/monster\ "facebook\ graph\ api"
  ./exe/monster\ "fail2ban"
  ./exe/monster\ "git"
  ./exe/monster\ "github"
  ./exe/monster\ "github\ api"
  ./exe/monster\ "gitlab"
  ./exe/monster\ "go"
  ./exe/monster\ "golang"
  ./exe/monster\ "google\ analytics"
  ./exe/monster\ "graph\ api"
  ./exe/monster\ "hadoop"
  ./exe/monster\ "heroku"
  ./exe/monster\ "html"
  ./exe/monster\ "html5"
  ./exe/monster\ "http"
  ./exe/monster\ "hubot"
  ./exe/monster\ "instagram\ api"
  ./exe/monster\ "java"
  ./exe/monster\ "javascript"
  ./exe/monster\ "jira"
  ./exe/monster\ "jquery"
  ./exe/monster\ "jruby"
  ./exe/monster\ "json"
  ./exe/monster\ "json\ api"
  ./exe/monster\ "jsonapi"
  ./exe/monster\ "jwt"
  ./exe/monster\ "kafka"
  ./exe/monster\ "kubernetes"
  ./exe/monster\ "linux"
  ./exe/monster\ "lisp"
  ./exe/monster\ "lodash"
  ./exe/monster\ "logentries"
  ./exe/monster\ "markdown"
  ./exe/monster\ "memcached"
  ./exe/monster\ "middleware"
  ./exe/monster\ "mongodb"
  ./exe/monster\ "mongrel"
  ./exe/monster\ "monit"
  ./exe/monster\ "mssql"
  ./exe/monster\ "mysql"
  ./exe/monster\ "neovim"
  ./exe/monster\ "new\ relic"
  ./exe/monster\ "nginx"
  ./exe/monster\ "node.js"
  ./exe/monster\ "nodejs"
  ./exe/monster\ "openstack"
  ./exe/monster\ "passenger"
  ./exe/monster\ "php"
  ./exe/monster\ "phpunit"
  ./exe/monster\ "postgres"
  ./exe/monster\ "postgresql"
  ./exe/monster\ "programming"
  ./exe/monster\ "prolog"
  ./exe/monster\ "puma"
  ./exe/monster\ "puppet"
  ./exe/monster\ "python"
  ./exe/monster\ "qunit"
  ./exe/monster\ "rails"
  ./exe/monster\ "raphael.js"
  ./exe/monster\ "rds"
  ./exe/monster\ "react"
  ./exe/monster\ "redis"
  ./exe/monster\ "redux"
  ./exe/monster\ "resque"
  ./exe/monster\ "rest"
  ./exe/monster\ "riak"
  ./exe/monster\ "rollbar"
  ./exe/monster\ "rspec"
  ./exe/monster\ "ruby"
  ./exe/monster\ "ruby\ on\ rails"
  ./exe/monster\ "rust"
  ./exe/monster\ "s3"
  ./exe/monster\ "sass"
  ./exe/monster\ "scala"
  ./exe/monster\ "scrum"
  ./exe/monster\ "semaphore\ ci"
  ./exe/monster\ "sendgrid\ api"
  ./exe/monster\ "shell"
  ./exe/monster\ "sidekiq"
  ./exe/monster\ "soap"
  ./exe/monster\ "sql"
  ./exe/monster\ "stripe"
  ./exe/monster\ "subversion"
  ./exe/monster\ "sumo\ logic"
  ./exe/monster\ "t-sql"
  ./exe/monster\ "thin"
  ./exe/monster\ "transact-sql"
  ./exe/monster\ "trello"
  ./exe/monster\ "twitter\ api"
  ./exe/monster\ "typescript"
  ./exe/monster\ "ubuntu"
  ./exe/monster\ "uml"
  ./exe/monster\ "underscore.js"
  ./exe/monster\ "unicorn"
  ./exe/monster\ "vagrant"
  ./exe/monster\ "vertica"
  ./exe/monster\ "vim"
  ./exe/monster\ "viml"
  ./exe/monster\ "vmware"
  ./exe/monster\ "web\ api"
  ./exe/monster\ "xhtml"
  ./exe/monster\ "xml"
  ./exe/monster\ "yaml"
  ./exe/monster\ "z\ shell"
  ./exe/monster\ "zsh"
  ./exe/nexxt
  ./exe/nexxt\ "a11y"
  ./exe/nexxt\ "agile"
  ./exe/nexxt\ "airbrake"
  ./exe/nexxt\ "ansible"
  ./exe/nexxt\ "apache"
  ./exe/nexxt\ "api"
  ./exe/nexxt\ "aws"
  ./exe/nexxt\ "backbone.js"
  ./exe/nexxt\ "bash"
  ./exe/nexxt\ "bootstrap"
  ./exe/nexxt\ "capistrano"
  ./exe/nexxt\ "ccnet"
  ./exe/nexxt\ "centos"
  ./exe/nexxt\ "chargify"
  ./exe/nexxt\ "circle\ ci"
  ./exe/nexxt\ "clojure"
  ./exe/nexxt\ "codesmith\ api"
  ./exe/nexxt\ "coffeescript"
  ./exe/nexxt\ "couchdb"
  ./exe/nexxt\ "css"
  ./exe/nexxt\ "cucumber"
  ./exe/nexxt\ "devops"
  ./exe/nexxt\ "digitalocean"
  ./exe/nexxt\ "docker"
  ./exe/nexxt\ "ec2"
  ./exe/nexxt\ "elasticsearch"
  ./exe/nexxt\ "ember.js"
  ./exe/nexxt\ "emberjs"
  ./exe/nexxt\ "eruby"
  ./exe/nexxt\ "etl"
  ./exe/nexxt\ "facebook\ graph\ api"
  ./exe/nexxt\ "fail2ban"
  ./exe/nexxt\ "git"
  ./exe/nexxt\ "github"
  ./exe/nexxt\ "github\ api"
  ./exe/nexxt\ "gitlab"
  ./exe/nexxt\ "go"
  ./exe/nexxt\ "golang"
  ./exe/nexxt\ "google\ analytics"
  ./exe/nexxt\ "graph\ api"
  ./exe/nexxt\ "hadoop"
  ./exe/nexxt\ "heroku"
  ./exe/nexxt\ "html"
  ./exe/nexxt\ "html5"
  ./exe/nexxt\ "http"
  ./exe/nexxt\ "hubot"
  ./exe/nexxt\ "instagram\ api"
  ./exe/nexxt\ "java"
  ./exe/nexxt\ "javascript"
  ./exe/nexxt\ "jira"
  ./exe/nexxt\ "jquery"
  ./exe/nexxt\ "jruby"
  ./exe/nexxt\ "json"
  ./exe/nexxt\ "json\ api"
  ./exe/nexxt\ "jsonapi"
  ./exe/nexxt\ "jwt"
  ./exe/nexxt\ "kafka"
  ./exe/nexxt\ "kubernetes"
  ./exe/nexxt\ "linux"
  ./exe/nexxt\ "lisp"
  ./exe/nexxt\ "lodash"
  ./exe/nexxt\ "logentries"
  ./exe/nexxt\ "markdown"
  ./exe/nexxt\ "memcached"
  ./exe/nexxt\ "middleware"
  ./exe/nexxt\ "mongodb"
  ./exe/nexxt\ "mongrel"
  ./exe/nexxt\ "monit"
  ./exe/nexxt\ "mssql"
  ./exe/nexxt\ "mysql"
  ./exe/nexxt\ "neovim"
  ./exe/nexxt\ "new\ relic"
  ./exe/nexxt\ "nginx"
  ./exe/nexxt\ "node.js"
  ./exe/nexxt\ "nodejs"
  ./exe/nexxt\ "openstack"
  ./exe/nexxt\ "passenger"
  ./exe/nexxt\ "php"
  ./exe/nexxt\ "phpunit"
  ./exe/nexxt\ "postgres"
  ./exe/nexxt\ "postgresql"
  ./exe/nexxt\ "programming"
  ./exe/nexxt\ "prolog"
  ./exe/nexxt\ "puma"
  ./exe/nexxt\ "puppet"
  ./exe/nexxt\ "python"
  ./exe/nexxt\ "qunit"
  ./exe/nexxt\ "rails"
  ./exe/nexxt\ "raphael.js"
  ./exe/nexxt\ "rds"
  ./exe/nexxt\ "react"
  ./exe/nexxt\ "redis"
  ./exe/nexxt\ "redux"
  ./exe/nexxt\ "resque"
  ./exe/nexxt\ "rest"
  ./exe/nexxt\ "riak"
  ./exe/nexxt\ "rollbar"
  ./exe/nexxt\ "rspec"
  ./exe/nexxt\ "ruby"
  ./exe/nexxt\ "ruby\ on\ rails"
  ./exe/nexxt\ "rust"
  ./exe/nexxt\ "s3"
  ./exe/nexxt\ "sass"
  ./exe/nexxt\ "scala"
  ./exe/nexxt\ "scrum"
  ./exe/nexxt\ "semaphore\ ci"
  ./exe/nexxt\ "sendgrid\ api"
  ./exe/nexxt\ "shell"
  ./exe/nexxt\ "sidekiq"
  ./exe/nexxt\ "soap"
  ./exe/nexxt\ "sql"
  ./exe/nexxt\ "stripe"
  ./exe/nexxt\ "subversion"
  ./exe/nexxt\ "sumo\ logic"
  ./exe/nexxt\ "t-sql"
  ./exe/nexxt\ "thin"
  ./exe/nexxt\ "transact-sql"
  ./exe/nexxt\ "trello"
  ./exe/nexxt\ "twitter\ api"
  ./exe/nexxt\ "typescript"
  ./exe/nexxt\ "ubuntu"
  ./exe/nexxt\ "uml"
  ./exe/nexxt\ "underscore.js"
  ./exe/nexxt\ "unicorn"
  ./exe/nexxt\ "vagrant"
  ./exe/nexxt\ "vertica"
  ./exe/nexxt\ "vim"
  ./exe/nexxt\ "viml"
  ./exe/nexxt\ "vmware"
  ./exe/nexxt\ "web\ api"
  ./exe/nexxt\ "xhtml"
  ./exe/nexxt\ "xml"
  ./exe/nexxt\ "yaml"
  ./exe/nexxt\ "z\ shell"
  ./exe/nexxt\ "zsh"
  ./exe/remoteok
  ./exe/remotepython
  ./exe/stackoverflow\ "a11y"
  ./exe/stackoverflow\ "agile"
  ./exe/stackoverflow\ "airbrake"
  ./exe/stackoverflow\ "ansible"
  ./exe/stackoverflow\ "apache"
  ./exe/stackoverflow\ "api"
  ./exe/stackoverflow\ "aws"
  ./exe/stackoverflow\ "backbone.js"
  ./exe/stackoverflow\ "bash"
  ./exe/stackoverflow\ "bootstrap"
  ./exe/stackoverflow\ "capistrano"
  ./exe/stackoverflow\ "ccnet"
  ./exe/stackoverflow\ "centos"
  ./exe/stackoverflow\ "chargify"
  ./exe/stackoverflow\ "circle\ ci"
  ./exe/stackoverflow\ "clojure"
  ./exe/stackoverflow\ "codesmith\ api"
  ./exe/stackoverflow\ "coffeescript"
  ./exe/stackoverflow\ "couchdb"
  ./exe/stackoverflow\ "css"
  ./exe/stackoverflow\ "cucumber"
  ./exe/stackoverflow\ "devops"
  ./exe/stackoverflow\ "digitalocean"
  ./exe/stackoverflow\ "docker"
  ./exe/stackoverflow\ "ec2"
  ./exe/stackoverflow\ "elasticsearch"
  ./exe/stackoverflow\ "ember.js"
  ./exe/stackoverflow\ "emberjs"
  ./exe/stackoverflow\ "eruby"
  ./exe/stackoverflow\ "etl"
  ./exe/stackoverflow\ "facebook\ graph\ api"
  ./exe/stackoverflow\ "fail2ban"
  ./exe/stackoverflow\ "git"
  ./exe/stackoverflow\ "github"
  ./exe/stackoverflow\ "github\ api"
  ./exe/stackoverflow\ "gitlab"
  ./exe/stackoverflow\ "go"
  ./exe/stackoverflow\ "golang"
  ./exe/stackoverflow\ "google\ analytics"
  ./exe/stackoverflow\ "graph\ api"
  ./exe/stackoverflow\ "hadoop"
  ./exe/stackoverflow\ "heroku"
  ./exe/stackoverflow\ "html"
  ./exe/stackoverflow\ "html5"
  ./exe/stackoverflow\ "http"
  ./exe/stackoverflow\ "hubot"
  ./exe/stackoverflow\ "instagram\ api"
  ./exe/stackoverflow\ "java"
  ./exe/stackoverflow\ "javascript"
  ./exe/stackoverflow\ "jira"
  ./exe/stackoverflow\ "jquery"
  ./exe/stackoverflow\ "jruby"
  ./exe/stackoverflow\ "json"
  ./exe/stackoverflow\ "json\ api"
  ./exe/stackoverflow\ "jsonapi"
  ./exe/stackoverflow\ "jwt"
  ./exe/stackoverflow\ "kafka"
  ./exe/stackoverflow\ "kubernetes"
  ./exe/stackoverflow\ "linux"
  ./exe/stackoverflow\ "lisp"
  ./exe/stackoverflow\ "lodash"
  ./exe/stackoverflow\ "logentries"
  ./exe/stackoverflow\ "markdown"
  ./exe/stackoverflow\ "memcached"
  ./exe/stackoverflow\ "middleware"
  ./exe/stackoverflow\ "mongodb"
  ./exe/stackoverflow\ "mongrel"
  ./exe/stackoverflow\ "monit"
  ./exe/stackoverflow\ "mssql"
  ./exe/stackoverflow\ "mysql"
  ./exe/stackoverflow\ "new\ relic"
  ./exe/stackoverflow\ "nginx"
  ./exe/stackoverflow\ "node.js"
  ./exe/stackoverflow\ "nodejs"
  ./exe/stackoverflow\ "openstack"
  ./exe/stackoverflow\ "passenger"
  ./exe/stackoverflow\ "php"
  ./exe/stackoverflow\ "phpunit"
  ./exe/stackoverflow\ "postgres"
  ./exe/stackoverflow\ "postgresql"
  ./exe/stackoverflow\ "programming"
  ./exe/stackoverflow\ "prolog"
  ./exe/stackoverflow\ "puma"
  ./exe/stackoverflow\ "puppet"
  ./exe/stackoverflow\ "python"
  ./exe/stackoverflow\ "qunit"
  ./exe/stackoverflow\ "rails"
  ./exe/stackoverflow\ "raphael.js"
  ./exe/stackoverflow\ "rds"
  ./exe/stackoverflow\ "react"
  ./exe/stackoverflow\ "redis"
  ./exe/stackoverflow\ "redux"
  ./exe/stackoverflow\ "resque"
  ./exe/stackoverflow\ "rest"
  ./exe/stackoverflow\ "riak"
  ./exe/stackoverflow\ "rollbar"
  ./exe/stackoverflow\ "rspec"
  ./exe/stackoverflow\ "ruby"
  ./exe/stackoverflow\ "ruby\ on\ rails"
  ./exe/stackoverflow\ "rust"
  ./exe/stackoverflow\ "s3"
  ./exe/stackoverflow\ "sass"
  ./exe/stackoverflow\ "scala"
  ./exe/stackoverflow\ "scrum"
  ./exe/stackoverflow\ "semaphore\ ci"
  ./exe/stackoverflow\ "sendgrid\ api"
  ./exe/stackoverflow\ "shell"
  ./exe/stackoverflow\ "sidekiq"
  ./exe/stackoverflow\ "soap"
  ./exe/stackoverflow\ "sql"
  ./exe/stackoverflow\ "stripe"
  ./exe/stackoverflow\ "subversion"
  ./exe/stackoverflow\ "sumo\ logic"
  ./exe/stackoverflow\ "t-sql"
  ./exe/stackoverflow\ "thin"
  ./exe/stackoverflow\ "transact-sql"
  ./exe/stackoverflow\ "trello"
  ./exe/stackoverflow\ "twitter\ api"
  ./exe/stackoverflow\ "typescript"
  ./exe/stackoverflow\ "ubuntu"
  ./exe/stackoverflow\ "uml"
  ./exe/stackoverflow\ "underscore.js"
  ./exe/stackoverflow\ "unicorn"
  ./exe/stackoverflow\ "vagrant"
  ./exe/stackoverflow\ "vertica"
  ./exe/stackoverflow\ "vim"
  ./exe/stackoverflow\ "viml"
  ./exe/stackoverflow\ "vmware"
  ./exe/stackoverflow\ "web\ api"
  ./exe/stackoverflow\ "xhtml"
  ./exe/stackoverflow\ "xml"
  ./exe/stackoverflow\ "yaml"
  ./exe/stackoverflow\ "z\ shell"
  ./exe/stackoverflow\ "zsh"
  ./exe/weworkremotely
].uniq.freeze

require 'whenever'

env 'MAILTO', 'mike@just3ws.com'

set :job_template, "/usr/bin/env bash -l -c ':job' "
set :output, '/home/ubuntu/outlier_jobs/shared/log/cron_production.log'

JOB_PREFIX = ' cd :path && :environment_variable=:environment nice -n 20 '

job_type :rails,  " #{JOB_PREFIX} bundle exec rails :task --silent :output "
job_type :script, " #{JOB_PREFIX} bundle exec bin/:task :output "
job_type :runner, " #{JOB_PREFIX} bin/rails runner :task :output "
job_type :command,  " #{JOB_PREFIX} :task :output "

def planner(slots:, duration:)
  count_from = ((duration.to_f / slots.count) / 2).to_i
  count_by = duration.to_f / (slots.count + 1)

  count_from.step(duration, count_by).map(&:to_i).zip(slots)
end

CRONS = %i[cron1 cron2].freeze

def scheduler(start_at:, slots:)
  slots.each_with_index do |slot, i|
    time = start_at + slot.first

    cron = "#{time.min} #{time.hour} * * *"
    task = slot.last

    next if task.to_s.strip.empty?

    host = CRONS[i.even? ? 0 : 1]

    every(cron, roles: [host]) { runner task.to_s.strip }
  end
end

every('3,33 * * * *', roles: [:cron1]) { runner './exe/messages' }
every('18,48 * * * *', roles: [:cron2]) { runner './exe/messages' }

every('7,37 * * * *', roles: [:cron1]) { runner './exe/moment' }
every('22,57 * * * *', roles: [:cron2]) { runner './exe/moment' }

every('8 * * * *', roles: [:cron1]) { runner './exe/tags' }
every('38 * * * *', roles: [:cron2]) { runner './exe/tags' }

scheduler(
  start_at: Date.today.to_datetime.to_time.utc,
  slots: planner(slots: TASKS.shuffle.freeze, duration: 1.day)
)

every(1.day, roles: [:cron1]) { rake 'pghero:capture_space_stats' }
every(9.minutes, roles: [:cron2]) { rake 'pghero:capture_query_stats' }
