---
shared:
  terms:
    - apache
    - as400
    - bash
    - clojure
    - cobol
    - csharp
    - docker
    - dotnet
    - flask
    - golang
    - java
    - javascript
    - json
    - jvm
    - kafka
    - kotlin
    - kubernetes
    - linux
    - macos
    - nginx
    - node
    - nodejs
    - ops
    - postgresql
    - python
    - rails
    - react
    - redis
    - resque
    - rspec
    - ruby
    - rust
    - sidekiq
    - spark
    - sql
    - swift
    - typescript
    - zsh
