#!/usr/bin/env bash

bundle exec rails runner exe/hackernews
bundle exec rails runner exe/indeed
bundle exec rails runner exe/monster
bundle exec rails runner exe/nexxt
bundle exec rails runner exe/remoteok
bundle exec rails runner exe/remotepython
bundle exec rails runner exe/stackoverflow
bundle exec rails runner exe/weworkremotely

bundle exec rails runner exe/job_postings
