#!/usr/bin/env bash

DATE="$(date -u +'%Y-%m-%d')"
mkdir -p "/home/ubuntu/outlier_jobs/shared/data/dice/$DATE"
cd "/home/ubuntu/outlier_jobs/shared/data/dice/$DATE" || exit

wget https://rss.dice.com/generic/all_jobs.xml.gz --header="Accept: application/octet-stream"
gunzip all_jobs.xml.gz
xml_split -l2 all_jobs.xml
rm -f all_jobs.xml
