#!/usr/bin/env zsh

mkdir -p ~/projects/wwworkremote/hosts/

cd ~/projects/wwworkremote/hosts

for host in {malina101,malina102,malina103,malina104,malina108,jagodka105} ; do 
  echo 
  echo '------------------------------'
  echo 
  echo "$host"
  echo
  echo '------------------------------'
  echo 

  mkdir -p ~/projects/wwworkremote/hosts/$host/etc/nginx/sites-available/
  mkdir -p ~/projects/wwworkremote/hosts/$host/etc/redis/
  mkdir -p ~/projects/wwworkremote/hosts/$host/etc/systemd/system/
  mkdir -p ~/projects/wwworkremote/hosts/$host/mike/
  mkdir -p ~/projects/wwworkremote/hosts/$host/root/
  mkdir -p ~/projects/wwworkremote/hosts/$host/var/lib/postgres/data/

  mkdir -p ~/projects/wwworkremote/hosts/$host/deploy/.config/
  mkdir -p ~/projects/wwworkremote/hosts/$host/deploy/bin/
  mkdir -p ~/projects/wwworkremote/hosts/$host/deploy/projects/wwworkremote/core/shared/config/
  mkdir -p ~/projects/wwworkremote/hosts/$host/deploy/projects/wwworkremote/dashboard/shared/config/

  scp $host:~/.\*hist\* ~/projects/wwworkremote/hosts/$host/deploy/
  scp $host:~/.\*hst\* ~/projects/wwworkremote/hosts/$host/deploy/
  scp $host:~/.asdfrc ~/projects/wwworkremote/hosts/$host/deploy/
  scp $host:~/.bash\* ~/projects/wwworkremote/hosts/$host/deploy/
  scp $host:~/.default\* ~/projects/wwworkremote/hosts/$host/deploy/
  scp $host:~/.dir_colors ~/projects/wwworkremote/hosts/$host/deploy/
  scp $host:~/.gemrc ~/projects/wwworkremote/hosts/$host/deploy/
  scp $host:~/.hushlogin ~/projects/wwworkremote/hosts/$host/deploy/
  scp $host:~/.profile ~/projects/wwworkremote/hosts/$host/deploy/
  scp $host:~/.tool-versions ~/projects/wwworkremote/hosts/$host/deploy/

  scp -r $host:~/.config/ ~/projects/wwworkremote/hosts/$host/deploy/
  rm -rf ~/projects/wwworkremote/hosts/$host/deploy/.config/tmux/plugins/

  scp -r $host:~/bin/ ~/projects/wwworkremote/hosts/$host/deploy/

  scp -r $host:~/.ssh/ ~/projects/wwworkremote/hosts/$host/deploy/

  scp -r $host:~/projects/wwworkremote/core/shared/config/ ~/projects/wwworkremote/hosts/$host/deploy/projects/wwworkremote/core/shared/
  scp -r $host:~/projects/wwworkremote/dashboard/shared/config/ ~/projects/wwworkremote/hosts/$host/deploy/projects/wwworkremote/dashboard/shared/

  ssh $host "mkdir -p ~/backup/root/"
  ssh $host "mkdir -p ~/backup/mike/"

  ssh $host "sudo cp /etc/nginx/nginx.conf ~/backup/"
  ssh $host "sudo cp /etc/nginx/sites-available/dashboard ~/backup/"
  ssh $host "sudo cp /etc/redis/redis.conf ~/backup/"
  ssh $host "sudo cp /etc/rsyslog.conf ~/backup/"
  ssh $host "sudo cp /etc/sudoers ~/backup/"
  ssh $host "sudo cp /etc/systemd/journald.conf ~/backup/"
  ssh $host "sudo cp /etc/systemd/puma.service ~/backup/"
  ssh $host "sudo cp /etc/systemd/system/data-backup.automount ~/backup/"
  ssh $host "sudo cp /etc/systemd/system/data-backup.mount ~/backup/"
  ssh $host "sudo cp /var/lib/postgres/data/pg_hba.conf ~/backup/"
  ssh $host "sudo cp /var/lib/postgres/data/postgresql.conf ~/backup/"

  ssh $host "sudo cp /root/.bash_history ~/backup/root/"
  ssh $host "sudo cp /home/mike/.bash_history ~/backup/mike/"

  ssh $host "sudo chown -R deploy:deploy ~/backup/"

  scp $host:~/backup/root/.bash_history ~/projects/wwworkremote/hosts/$host/root/
  scp $host:~/backup/root/.lesshst ~/projects/wwworkremote/hosts/$host/root/
  scp $host:~/backup/root/.python_history ~/projects/wwworkremote/hosts/$host/root/

  scp $host:~/backup/mike/.bash_history ~/projects/wwworkremote/hosts/$host/mike/
  scp $host:~/backup/mike/.lesshst ~/projects/wwworkremote/hosts/$host/mike/
  scp $host:~/backup/mike/.python_history ~/projects/wwworkremote/hosts/$host/mike/

  scp $host:~/backup/dashboard ~/projects/wwworkremote/hosts/$host/etc/nginx/sites-available/
  scp $host:~/backup/journald.conf ~/projects/wwworkremote/hosts/$host/etc/systemd/
  scp $host:~/backup/nginx.conf ~/projects/wwworkremote/hosts/$host/etc/nginx/
  scp $host:~/backup/pg_hba.conf ~/projects/wwworkremote/hosts/$host/var/lib/postgres/data/
  scp $host:~/backup/postgresql.conf ~/projects/wwworkremote/hosts/$host/var/lib/postgres/data/
  scp $host:~/backup/puma.service ~/projects/wwworkremote/hosts/$host/etc/systemd/
  scp $host:~/backup/redis.conf ~/projects/wwworkremote/hosts/$host/etc/redis/
  scp $host:~/backup/rsyslog.conf ~/projects/wwworkremote/hosts/$host/etc/
  scp $host:~/backup/sudoers ~/projects/wwworkremote/hosts/$host/etc/

  scp $host:~/backup/data-backup.mount ~/projects/wwworkremote/hosts/$host/etc/systemd/system/
  scp $host:~/backup/data-backup.automount ~/projects/wwworkremote/hosts/$host/etc/systemd/system/

  ssh $host cat /etc/group >! ~/projects/wwworkremote/hosts/$host/etc/group
  ssh $host cat /etc/passwd >! ~/projects/wwworkremote/hosts/$host/etc/passwd
  ssh $host cat /etc/hosts >! ~/projects/wwworkremote/hosts/$host/etc/hosts

  ssh $host crontab -l >! ~/projects/wwworkremote/hosts/$host/crontab.txt
  ssh $host env >! ~/projects/wwworkremote/hosts/$host/deploy/env.txt
  ssh $host pacman -Q >! ~/projects/wwworkremote/hosts/$host/pacman.txt
  ssh $host systemctl --type=service >! ~/projects/wwworkremote/hosts/$host/systemd-services.txt
done

ls -alh ~/projects/wwworkremote/hosts

cd ~/projects/wwworkremote/hosts

find ~/projects/wwworkremote/hosts -type f -name .DS_Store -delete 
find ~/projects/wwworkremote/hosts -type f -empty -delete
find ~/projects/wwworkremote/hosts -type d -empty -delete

mkdir -p ~/Dropbox/mike/projects/wwworkremote/backups/
cp -r ~/projects/wwworkremote/hosts ~/Dropbox/mike/projects/wwworkremote/backups/
