---
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sentry:
    runs-on: ubuntu-latest
    env:
      SENTRY_ORG: just3ws
      SENTRY_AUTH_TOKEN: '0e29254fac624501bae3c56d405d07b26863e9f1485b44c3aa5b12226d5157b7'
      SENTRY_PROJECT: outlier_jobs
    steps:
      - uses: actions/checkout@v2
      - name: Sentry Release
        uses: getsentry/action-release@v1.1.5
